{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bank-account.serviceAccountName" . }}
  labels:
{{ include "bank-account.labels" . | indent 4 }}
{{- end -}}
