apiVersion: v1
kind: Service
metadata:
  name: bank-account
spec:
  selector:
    app: bank-account
  #type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30200