apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: bank-ms-account-nodeport-yaml
spec:
  type: NodePort
  selector:
    app: bank-ms-account
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      