apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-ms-account-deployment
  labels:
    app: bank-ms-account
spec:
  selector:
    matchLabels:
      app: bank-ms-account
  template:
    metadata:
      labels:
        app: bank-ms-account
    spec:
      containers:
      - name: bank-ms-account
        image: pauloneves/bank-ms-account:0.0.1
        ports:
        - containerPort: 8080
