apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-account.name" . }}
  labels:
    {{- include "bank-account.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "bank-account.selectorLabels" . | nindent 4 }}
